(() => {
  const canvas = document.getElementById('adventureCanvas');
  const ctx = canvas.getContext('2d');
  const W = 960, H = 540, GRAVITY = 0.55;
  function resizeCanvas() { const ratio=Math.min(window.devicePixelRatio||1,2); canvas.width=W*ratio; canvas.height=H*ratio; ctx.setTransform(ratio,0,0,ratio,0,0); }
  resizeCanvas();
  window.addEventListener('resize',resizeCanvas);
  const keys = new Set(), keyboardKeys = new Set();
  const modeMenu = document.getElementById('modeMenu');
  const quizApp = document.getElementById('quizApp');
  const gameApp = document.getElementById('gameApp');
  const RUN_SECONDS = 600, RUN_HISTORY_KEY = 'minecraft-adventure-history-v1';
  let levelIndex = 0, level, player, camera = 0, running = false, last = 0, message = '', messageTimer = 0, totalLives = 20, selectedLives = 20, selectedDifficulty = 'normal', chapterDeaths = 0, audioContext, musicTimer, musicOn = false, projectiles = [], endingStart = 0, runStartedAt = 0, score = 0, kills = 0, bosses = 0, runRecorded = false, activeNotes = [], finalScoreTarget = 0;

  const themes = [
    { name: '01 · 出生点：橡木平原', sky: '#87c9ed', far: '#73aa57', ground: '#6d9f42', dirt: '#8a5b39', gem: '绿宝石', tip: '收集绿宝石，抵达村庄传送门。' },
    { name: '02 · 深板岩矿洞', sky: '#33455b', far: '#263443', ground: '#65727b', dirt: '#3d4a52', gem: '钻石', tip: '小心岩浆，利用梯子和矿车轨道前进。' },
    { name: '03 · 下界荒原', sky: '#6a2630', far: '#491b24', ground: '#8c3b36', dirt: '#4e2026', gem: '下界石英', tip: '岩浆会让你回到检查点。' },
    { name: '04 · 下界要塞', sky: '#321c2c', far: '#241521', ground: '#6b3940', dirt: '#3a2227', gem: '烈焰棒', tip: '跨过堡垒断桥，寻找末影珍珠。' },
    { name: '05 · 要塞：末地传送门', sky: '#36454c', far: '#26343a', ground: '#78846f', dirt: '#4c554a', gem: '末影之眼', tip: '在要塞深处集齐末影之眼。' },
    { name: '06 · 末地：终末之战', sky: '#171329', far: '#2d2350', ground: '#746b98', dirt: '#3e365f', gem: '末地水晶', tip: '按 F 发射箭矢，击败末影龙后进入终点。' }
  ];
  const chapterHelp = [
    '平原：踩怪、收集绿宝石，抵达村庄传送门。',
    '矿洞：断崖只能通过水平与垂直矿车跨越。',
    '下界：灵魂沙会减速；踩上黏液弹射台越过岩浆；注意坍塌方块。',
    '要塞：踩下红石压力板打开砖门；利用矿车与烈焰机关前进。',
    '要塞深处：收集末影之眼、避开银鱼砖陷阱，打开末地门。',
    '末地：跨越空岛，躲避龙息与弹幕；按 F 射击末影龙。'
  ];

  const layouts = [
    [[0,470,360],[420,430,110],[590,380,105],[760,435,80],[905,350,120],[1085,400,150],[1300,325,90],[1450,390,180],[1700,340,135],[1900,405,110],[2080,455,500]],
    [[0,470,300],[680,420,160],[1000,260,170],[1600,350,120],[1880,300,160],[2160,450,420]],
    [[0,470,330],[400,420,95],[560,340,100],[730,390,80],[875,295,125],[1070,370,115],[1540,300,260],[1870,365,145],[2030,450,550]],
    [[0,470,290],[350,410,90],[510,350,110],[690,290,80],[830,360,115],[1005,315,135],[1205,395,80],[1280,350,110],[1650,275,210],[1870,350,150],[2050,400,100],[2200,450,400]],
    [[0,470,340],[410,425,95],[565,355,115],[745,300,75],[885,370,100],[1050,285,135],[1245,350,85],[1390,410,120],[1580,315,140],[1785,365,90],[1945,300,115],[2130,450,460]],
    [[0,470,300],[380,420,100],[550,345,120],[740,395,85],[900,300,130],[1100,365,100],[1260,310,120],[1450,400,70],[1800,335,150],[1980,360,140],[2180,300,130],[2350,390,80],[2650,320,160],[2860,250,130],[3050,350,150],[3260,450,400]]
  ];
  const gemPositions = [
    [[250,410],[745,370],[950,310],[1200,360],[1460,290],[1720,345]],
    [[220,410],[610,360],[840,290],[1090,350],[1360,270],[1580,340]],
    [[230,410],[650,350],[900,290],[1100,370],[1360,270],[1590,325],[1820,260]],
    [[210,410],[560,350],[760,290],[990,240],[1240,320],[1450,270],[1710,340]],
    [[220,410],[670,370],[880,305],[1110,245],[1380,300],[1620,360],[1880,280]],
    [[250,410],[630,355],[850,290],[1090,340],[1310,260],[1570,330],[1800,280]]
  ];
  const monsterSeeds = [
    [[260,442,'zombie'],[620,352,'zombie'],[1095,372,'slime'],[1510,362,'zombie'],[1760,312,'slime']],
    [[250,442,'spider'],[555,322,'spider'],[885,287,'skeleton'],[1215,272,'spider'],[1600,297,'skeleton']],
    [[235,442,'magma'],[585,312,'magma'],[890,267,'piglin'],[1280,297,'magma']],
    [[220,442,'wither'],[530,322,'wither'],[850,332,'blaze'],[1370,302,'wither'],[1735,322,'blaze']],
    [[260,442,'silverfish'],[580,327,'silverfish'],[900,342,'endermite'],[1260,322,'silverfish'],[1600,287,'endermite']],
    [[230,442,'enderman'],[550,317,'enderman'],[870,262,'enderman'],[1225,282,'enderman'],[1540,307,'enderman']]
  ];

  function createLevel(i) {
    const theme = themes[i];
    const platforms = layouts[i].map(([x, y, w]) => ({ x, y, w, h: H - y }));
    // 每一件物资直接放在平台上表面，绝不会生成到地形内部或空隙里。
    const gems = platforms.slice(1, -1).map((platform) => ({ x: Math.round(platform.x + platform.w / 2 - 12), y: platform.y - 24, taken: false }));
    const bosses = i >= 2 && i < 5 ? [{ x: i === 2 ? 1870 : 1650, y: i === 2 ? 323 : i === 3 ? 247 : 275, type: i === 2 ? 'piglinBrute' : i === 3 ? 'blazeBoss' : 'shulker', w: 42, h: 42, hp: i === 2 ? 2 : i + 1, cooldown: 100, alive: true }] : [];
    const carts = i === 1 ? [{ x:270,y:450,min:270,max:625,direction:1,axis:'x',w:55,h:20,dx:0,dy:0 },{ x:820,y:400,minY:260,maxY:400,direction:-1,axis:'y',w:55,h:20,dx:0,dy:0 },{ x:1250,y:330,min:1250,max:1550,direction:1,axis:'x',w:55,h:20,dx:0,dy:0 },{ x:1730,y:350,min:1730,max:1850,direction:1,axis:'x',w:55,h:20,dx:0,dy:0 }] : i === 5 ? [{x:1370,y:400,min:1370,max:1745,direction:1,axis:'x',w:55,h:20,dx:0,dy:0},{x:2300,y:390,minY:260,maxY:390,direction:-1,axis:'y',w:55,h:20,dx:0,dy:0}] : [];
    const interactives = i === 2 ? { slowZones:[{x:520,y:430,w:120,h:40}], launchPads:[{x:1185,y:355,w:50,h:14},{x:1320,y:315,w:50,h:14},{x:1450,y:285,w:50,h:14}], powerups:[{x:1760,y:272,type:'fire',taken:false}] } : i === 3 ? { switches:[{x:870,y:332,active:false}], doors:[{x:1190,y:315,w:26,h:80,open:false}], timedPlatforms:[{x:1465,y:245,w:65,h:15,ticks:0,label:3,fallen:false}], powerups:[{x:1760,y:312,type:'speed',taken:false}] } : i === 4 ? { switches:[{x:1080,y:270,active:false}], doors:[{x:1390,y:330,w:26,h:80,open:false}], traps:[{x:820,y:350,cooldown:90,sourceIndex:2}], powerups:[{x:1800,y:320,type:'jump',taken:false}] } : i === 5 ? { slowZones:[{x:560,y:430,w:110,h:40}], launchPads:[{x:1190,y:295,w:50,h:14},{x:1320,y:275,w:50,h:14}], switches:[{x:2020,y:340,active:false}], doors:[{x:2350,y:310,w:26,h:80,open:false}], timedPlatforms:[{x:2460,y:270,w:75,h:15,ticks:0,label:3,fallen:false}], temporary:[{x:2680,y:285,w:90,h:14,phase:0}], traps:[{x:1880,y:340,cooldown:130,sourceIndex:2}], powerups:[{x:2150,y:270,type:'jump',taken:false}], crystals:[{x:2780,y:210,taken:false},{x:3000,y:300,taken:false}] } : {};
    return { ...theme, platforms, gems, monsters: monsterSeeds[i].map(([x, y, type], n) => ({ x, y, type, w: type === 'enderman' ? 22 : 29, h: type === 'enderman' ? 42 : 28, min: x - 45, max: x + 45 + (n % 2) * 35, direction: n % 2 ? -1 : 1, dead: false, cooldown:150+n*25 })), bosses, carts, interactives, hazards: i === 2 ? [{ x: 330, w: 70 }, { x: 660, w: 70 }, { x: 1180, w: 360 }, { x: 1800, w: 70 }] : i === 5 ? [{x:300,w:80},{x:670,w:70},{x:1360,w:90},{x:2270,w:110},{x:2870,w:80}] : [], exit: { x: i === 5 ? 3350 : 2390, y: 390, open: i !== 5 }, dragon: i === 5 ? { x: 3040, y: 125, hp: 20, direction: 1, alive: true, cooldown: 120 } : null };
  }
  function startLevel(i = 0, keepLives = true) { levelIndex = i; if (!keepLives) { totalLives = selectedLives; score = 0; kills = 0; bosses = 0; runStartedAt = Date.now(); runRecorded = false; } chapterDeaths = 0; endingStart = 0; level = createLevel(i); player = { x: 90, y: 350, w: 30, h: 42, vx: 0, vy: 0, grounded: false, facing: 1, gems: 0, invuln: 0, ridingCart: null, power:'' }; camera = 0; projectiles = []; const touchFire=document.getElementById('touchFire'), touchActions=document.querySelector('.touch-actions');if(touchFire)touchFire.hidden=i!==5;if(touchActions)touchActions.classList.toggle('has-fire',i===5); const help=document.getElementById('gameHelp');if(help)help.innerHTML=`<span>${chapterHelp[i]}</span><span>移动：A / D 或 ← / →</span><span>跳跃：空格 / W / ↑</span>${i===5?'<span>末影龙：按 F 射击</span>':'<span>怪物：从头顶踩下去</span>'}`; message = level.tip; messageTimer = 210; }
  function rectsOverlap(a, b) { return a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y; }
  function isOnScreen(entity) { return entity.x + (entity.w || 0) > camera && entity.x < camera + W; }
  function enemySpeed(speed) { return speed; }
  function monsterSpeed(speed) { return speed; }
  function lifeBonus() { return selectedDifficulty === 'easy' ? 10 : selectedDifficulty === 'hard' ? 1500 : 150; }
  function monsterName(type) { return ({ zombie: '僵尸', slime: '史莱姆', spider: '洞穴蜘蛛', skeleton: '骷髅', magma: '岩浆怪', piglin: '猪灵', wither: '凋灵骷髅', blaze: '烈焰人', silverfish: '蠹虫', endermite: '末影螨', enderman: '末影人' })[type] || '怪物'; }
  function playNote(frequency, delay, duration) { const osc = audioContext.createOscillator(), gain = audioContext.createGain(); activeNotes.push(osc); osc.onended=()=>activeNotes=activeNotes.filter(note=>note!==osc); osc.type = 'triangle'; osc.frequency.value = frequency; gain.gain.setValueAtTime(0.0001, audioContext.currentTime + delay); gain.gain.exponentialRampToValueAtTime(0.035, audioContext.currentTime + delay + 0.03); gain.gain.exponentialRampToValueAtTime(0.0001, audioContext.currentTime + delay + duration); osc.connect(gain).connect(audioContext.destination); osc.start(audioContext.currentTime + delay); osc.stop(audioContext.currentTime + delay + duration + 0.02); }
  function playAmbientPhrase() { if (!musicOn || !audioContext) return; const normal = [[220,277,330,392,330,277],[196,247,294,370,294,247],[174,220,262,330,262,220],[220,262,330,440,330,262]]; const phrase = normal[levelIndex % normal.length]; phrase.forEach((note, i) => playNote(note, i * .42, .58)); }
  function toggleMusic() { const button = document.getElementById('musicToggle'); if (!audioContext) audioContext = new (window.AudioContext || window.webkitAudioContext)(); musicOn = !musicOn; if (musicOn) { audioContext.resume(); playAmbientPhrase(); musicTimer = setInterval(playAmbientPhrase, 3100); } else { clearInterval(musicTimer); activeNotes.forEach(note=>{try{note.stop()}catch{}}); activeNotes=[]; } button.textContent = `♫ 音乐：${musicOn ? '开' : '关'}`; button.setAttribute('aria-pressed', String(musicOn)); }
  function runTimeLeft() { return Math.max(0, RUN_SECONDS - Math.floor((Date.now() - runStartedAt) / 1000)); }
  function readRunHistory() { try { return JSON.parse(localStorage.getItem(RUN_HISTORY_KEY) || '[]'); } catch { return []; } }
  function renderRunHistory() { const list=document.getElementById('gameRecordList'), empty=document.getElementById('gameRecordEmpty'), records=readRunHistory(); if(!list||!empty)return; list.innerHTML=''; empty.hidden=records.length>0; records.forEach((record,i)=>{const row=document.createElement('li');row.innerHTML=`<span class="record-rank">${String(i+1).padStart(2,'0')}</span><span><strong>${record.outcome}</strong><br><span class="record-meta">第 ${record.chapter} 章 · 击杀 ${record.kills} · 物资 ${record.loot}</span></span><span class="record-score">${record.score}</span>`;list.appendChild(row);}); }
  function recordRun(outcome) { if(runRecorded || !runStartedAt)return; const loot=level?level.gems.filter(g=>g.taken).length:0, finalScore=score+totalLives*lifeBonus()+runTimeLeft(), records=readRunHistory(); records.unshift({outcome,chapter:levelIndex+1,kills,loot,score:finalScore,time:Date.now()}); localStorage.setItem(RUN_HISTORY_KEY,JSON.stringify(records.slice(0,20))); runRecorded=true;finalScoreTarget=finalScore;score=finalScore;renderRunHistory(); }
  function hurt() { if (player.invuln > 0 || !running) return; totalLives--; chapterDeaths++; if (totalLives <= 0) { running = false; recordRun('生命耗尽'); message = '生命耗尽！点击“重开本关”从出生点重新远征。'; messageTimer = 999999; return; } for(const platform of level.interactives.timedPlatforms||[]){platform.ticks=0;platform.label=3;platform.fallen=false;} player.x = 72; player.y = 300; player.vx = 0; player.vy = 0; player.invuln = 100; message = '失去 1 条生命，倒计时平台已重置。'; messageTimer = 120; }
  function update() {
    if (!running || !level) return;
    if (runTimeLeft() <= 0) { running=false; recordRun('时间耗尽'); message='600 秒远征时间已耗尽！点击“重开本关”重新开始。'; messageTimer=999999; return; }
    const left = keys.has('ArrowLeft') || keys.has('KeyA'), right = keys.has('ArrowRight') || keys.has('KeyD'), jumpHeld = keys.has('Space') || keys.has('ArrowUp') || keys.has('KeyW');
    if (left) { player.vx -= .65; player.facing = -1; } if (right) { player.vx += .65; player.facing = 1; }
    player.vx *= .91; player.vx = Math.max(-5.8, Math.min(5.8, player.vx)); if (jumpHeld && player.grounded) jump();
    player.vy += GRAVITY; player.x += player.vx; player.y += player.vy; player.grounded = false;
    for (const cart of level.carts) { cart.dx=0;cart.dy=0;if(cart.axis==='x'){cart.dx=cart.direction*1.35;cart.x+=cart.dx;if(cart.x<cart.min||cart.x>cart.max)cart.direction*=-1}else{cart.dy=cart.direction*1.1;cart.y+=cart.dy;if(cart.y<cart.minY||cart.y>cart.maxY)cart.direction*=-1} }
    if (player.ridingCart) { const cart=player.ridingCart; if (!level.carts.includes(cart) || player.x + player.w < cart.x - 8 || player.x > cart.x + cart.w + 8) player.ridingCart=null; else { player.x+=cart.dx; player.y=cart.y-player.h; player.vy=Math.min(0,player.vy); player.grounded=true; } }
    const it=level.interactives; const landingSurfaces = [...level.platforms, ...level.carts, ...(it.launchPads||[]), ...(it.timedPlatforms||[]).filter(platform=>!platform.fallen)];
    for (const p of landingSurfaces) if (player.x + player.w > p.x && player.x < p.x + p.w && player.y + player.h > p.y - Math.max(2, Math.abs(p.dy||0)+2) && player.y + player.h - player.vy <= p.y + Math.max(8, Math.abs(p.dy||0)+8) && player.vy >= -1) { player.y = p.y - player.h; player.vy = 0; player.grounded = true; player.ridingCart=level.carts.includes(p)?p:null; if(level.carts.includes(p)){player.x+=p.dx;player.y=p.y-player.h;} }
    for (const cart of level.carts) if (player.ridingCart!==cart&&player.y+player.h>cart.y+6&&player.y<cart.y+cart.h&&player.x+player.w>cart.x&&player.x<cart.x+cart.w&&player.vy<=0) { if(player.x+player.w/2<cart.x+cart.w/2){player.x=cart.x-player.w;player.vx=0}else{player.x=cart.x+cart.w;player.vx=0} }
    if (player.x < 0) player.x = 0; if (player.y > H + 100) hurt();
    for (const hazard of level.hazards) if (player.x + player.w > hazard.x && player.x < hazard.x + hazard.w && player.y + player.h > 450) hurt();
    for (const gem of level.gems) if (!gem.taken && rectsOverlap(player, { x: gem.x, y: gem.y, w: 24, h: 24 })) { gem.taken = true; player.gems++; score += 100; message=`获得${level.gem}！+100 分`; messageTimer=55; }
    for(const platform of it.timedPlatforms||[]) if(!platform.fallen&&player.x+player.w>platform.x&&player.x<platform.x+platform.w&&player.y+player.h<=platform.y+20){platform.ticks++;platform.label=Math.max(0,3-Math.floor(platform.ticks/60));if(platform.ticks>=180){platform.fallen=true;message='倒计时平台坍塌了！';messageTimer=55;}}
    for(const zone of it.slowZones||[]) if(rectsOverlap(player,zone)) player.vx*=.55;
    for(const pad of it.launchPads||[]) if(player.x+player.w>pad.x&&player.x<pad.x+pad.w&&player.y+player.h>=pad.y&&player.y+player.h<=pad.y+18&&player.vy>=0){player.vy=-14;message='黏液弹射！';messageTimer=45;}
    for(const block of it.crumble||[]) if(!block.fallen&&player.x+player.w>block.x&&player.x<block.x+block.w&&player.y+player.h>=block.y&&player.y+player.h<=block.y+18){block.timer++;if(block.timer>55){block.fallen=true;message='方块坍塌了！';messageTimer=55;}}
    for(const sw of it.switches||[]) if(!sw.active&&rectsOverlap(player,{x:sw.x,y:sw.y,w:24,h:16})){sw.active=true;(it.doors||[]).forEach(door=>door.open=true);message='红石机关已激活，砖门打开！';messageTimer=100;}
    for(const power of it.powerups||[]) if(!power.taken&&rectsOverlap(player,{x:power.x,y:power.y,w:20,h:24})){power.taken=true;player.power=power.type;message=power.type==='fire'?'获得抗火药水！':power.type==='speed'?'获得迅捷药水！':'获得跳跃药水！';messageTimer=100;}
    for(const trap of it.traps||[]){const source=level.monsters[trap.sourceIndex];if(!source||source.dead||!isOnScreen(source))continue;trap.cooldown--;if(trap.cooldown<=0){trap.cooldown=120;projectiles.push({x:source.x,y:source.y+10,vx:player.x>source.x?enemySpeed(2.2):-enemySpeed(2.2),vy:0,enemy:true,w:10,h:10});}}
    for(const crystal of it.crystals||[]) if(!crystal.taken&&rectsOverlap(player,{x:crystal.x,y:crystal.y,w:22,h:32})){crystal.taken=true;score+=100;message='末地水晶已摧毁！+100 分';messageTimer=80;}
    for (const monster of level.monsters) { if (monster.dead) continue; monster.x += monster.direction * monsterSpeed(monster.type === 'silverfish' ? 1.25 : .85); if (monster.x < monster.min || monster.x > monster.max) monster.direction *= -1; if(['skeleton','piglin','blaze','endermite'].includes(monster.type)&&isOnScreen(monster)){monster.cooldown--;if(monster.cooldown<=0){const cave=levelIndex===1;monster.cooldown=cave?300:180;const bulletSpeed=cave?1.5:2.1;projectiles.push({x:monster.x+monster.w/2,y:monster.y+10,vx:player.x>monster.x?enemySpeed(bulletSpeed):-enemySpeed(bulletSpeed),vy:0,enemy:true,w:9,h:9});}} if (rectsOverlap(player, monster)) { const stomp = player.vy > 0 && player.y + player.h - player.vy <= monster.y + 12; if (stomp) { monster.dead = true; player.vy = -8.5; kills++; score += 20; message = `踩败了${monsterName(monster.type)}！+20 分`; messageTimer = 55; } else hurt(); } }
    for (const boss of level.bosses) if (boss.alive) { if(isOnScreen(boss))boss.cooldown--; if (isOnScreen(boss)&&boss.cooldown <= 0) { boss.cooldown = levelIndex===2?125:levelIndex===4?150:90; const bulletSpeed=levelIndex===2?1.55:3.1; projectiles.push({ x: boss.x + boss.w / 2, y: boss.y + 18, vx: player.x > boss.x ? enemySpeed(bulletSpeed) : -enemySpeed(bulletSpeed), vy: enemySpeed(.2), enemy: true, w: 11, h: 11 }); } if (rectsOverlap(player, boss)) { const stomp = player.vy > 0 && player.y + player.h - player.vy <= boss.y + 12; if (stomp) { boss.hp--; player.vy = -9.5; message = `命中小 Boss！剩余生命：${boss.hp}`; messageTimer = 70; if (boss.hp <= 0) {boss.alive=false;bosses++;score+=200;message='击败小 Boss！+200 分';messageTimer=90;} } else hurt(); } }
    if (level.dragon?.alive) { const d = level.dragon; d.x += d.direction * monsterSpeed(2.25); if (d.x > 3480 || d.x < 2850) d.direction *= -1; if(isOnScreen(d))d.cooldown--; if (isOnScreen(d)&&d.cooldown <= 0) { d.cooldown = 120; const dx = (player.x + player.w / 2) - (d.x + 48), dy = (player.y + player.h / 2) - (d.y + 30), size = Math.hypot(dx, dy) || 1; projectiles.push({ x: d.x + 48, y: d.y + 30, vx: enemySpeed(dx / size * 4.4), vy: enemySpeed(dy / size * 4.4), enemy: true, w: 14, h: 14 }); } if (rectsOverlap(player, { x:d.x, y:d.y, w:95, h:48 })) hurt(); }
    projectiles = projectiles.filter((shot) => { shot.x += shot.vx; shot.y += shot.vy; if (shot.enemy && rectsOverlap(player, shot)) { hurt(); return false; } if (!shot.enemy && level.dragon?.alive && rectsOverlap(shot, { x:level.dragon.x, y:level.dragon.y, w:95, h:48 })) { level.dragon.hp--; message = `箭矢命中末影龙！剩余生命：${level.dragon.hp}`; messageTimer = 70; if (level.dragon.hp <= 0) { level.dragon.alive = false; level.exit.open = true; score+=3000; message = '击败末影龙！+3000 分，前往终末之门。'; messageTimer = 180; } return false; } return shot.x > -40 && shot.x < 3800 && shot.y > -40 && shot.y < H + 40; });
    if (level.exit.open && rectsOverlap(player, { x: level.exit.x, y: level.exit.y, w: 60, h: 65 })) completeLevel();
    player.invuln = Math.max(0, player.invuln - 1); camera += ((player.x - W * .38) - camera) * .08; camera = Math.max(0, Math.min(2600, camera)); messageTimer = Math.max(0, messageTimer - 1);
  }
  function jump() { if (running && player?.grounded) { player.vy = -11.2; player.grounded = false; player.ridingCart = null; } }
  function fire() { if (!running || levelIndex !== 5 || !level.dragon?.alive || projectiles.filter(p => !p.enemy).length > 2) return; projectiles.push({ x:player.x + (player.facing > 0 ? player.w : -10), y:player.y + 17, vx:player.facing * 9, vy:0, enemy:false, w:12, h:4 }); }
  function completeLevel() { const rewards=[200,400,600,800,1200,2000], reward=rewards[levelIndex]; score+=reward; if (levelIndex < themes.length - 1) { startLevel(levelIndex + 1); message=`抵达上一关终点！+${reward} 分`; messageTimer=110; } else { running = false; recordRun('通关'); endingStart = performance.now(); message=`终末之门已开启！+${reward} 分`; messageTimer = 180; } }
  function block(x, y, w, h, top, fill) { ctx.fillStyle = fill; ctx.fillRect(x, y, w, h); ctx.fillStyle = top; ctx.fillRect(x, y, w, 10); ctx.fillStyle = 'rgba(0,0,0,.15)'; for (let xx = x + 12; xx < x + w; xx += 27) for (let yy = y + 18; yy < y + h; yy += 27) ctx.fillRect(xx, yy, 4, 4); }
  function draw() {
    if (!level) return; const t = level; ctx.clearRect(0, 0, W, H); ctx.fillStyle = t.sky; ctx.fillRect(0,0,W,H); ctx.fillStyle = t.far; for(let x=-80-(camera*.2%160);x<W+160;x+=160){ctx.fillRect(x,H-230,90,230);ctx.fillRect(x+25,H-270,38,40)}
    ctx.save(); ctx.translate(-Math.floor(camera), 0);
    for (const p of t.platforms) block(p.x, p.y, p.w, p.h, t.ground, t.dirt);
    for (const h of t.hazards) { const lava = levelIndex === 2 || levelIndex === 3; ctx.fillStyle = lava ? '#e85a2e' : '#101922'; ctx.fillRect(h.x, 452, h.w, 88); if(lava){ctx.fillStyle='#ffb23c';ctx.fillRect(h.x,452,h.w,5)} }
    const lootColors = [['#33b95b','#c9ffc1'],['#44d8ee','#d8ffff'],['#eee5d0','#fffdf1'],['#f2a83b','#fff07a'],['#9bcf63','#e8ffb7'],['#d16aff','#ffe4ff']][levelIndex];
    for (const g of t.gems) if (!g.taken) { ctx.fillStyle = lootColors[0]; ctx.fillRect(g.x+5,g.y,14,24); ctx.fillStyle=lootColors[1]; ctx.fillRect(g.x+8,g.y+4,8,9); }
    for (const cart of t.carts) { ctx.fillStyle='#55595c';ctx.fillRect(cart.x,cart.y,cart.w,cart.h);ctx.fillStyle='#aeb4b4';ctx.fillRect(cart.x+5,cart.y+4,cart.w-10,6);ctx.fillStyle='#222';ctx.fillRect(cart.x+8,cart.y+cart.h-3,8,5);ctx.fillRect(cart.x+cart.w-16,cart.y+cart.h-3,8,5); }
    const inter=t.interactives;for(const pad of inter.launchPads||[]){ctx.fillStyle='#9b4bd5';ctx.fillRect(pad.x,pad.y,pad.w,pad.h);ctx.fillStyle='#f4a6ff';ctx.fillRect(pad.x+4,pad.y+3,pad.w-8,4);ctx.fillStyle='#fff2a6';ctx.fillText('✦',pad.x+15,pad.y-4)}for(const platform of inter.timedPlatforms||[])if(!platform.fallen){ctx.fillStyle='#d17835';ctx.fillRect(platform.x,platform.y,platform.w,platform.h);ctx.fillStyle='#fff0a3';ctx.fillText(String(platform.label??platform.seconds),platform.x+platform.w/2-4,platform.y+12)}
    const exit = t.exit; ctx.fillStyle = exit.open ? (levelIndex===5 ? '#6d3c94' : '#286b67') : '#5a6063'; ctx.fillRect(exit.x,exit.y,60,65); ctx.fillStyle=exit.open?'#9ee5d8':'#262d30';ctx.fillRect(exit.x+9,exit.y+9,42,47);ctx.fillStyle='#dae867';ctx.fillRect(exit.x+23,exit.y+23,14,14);
    for (const monster of t.monsters) if (!monster.dead) { const c = ({zombie:'#4b9a61',slime:'#79bf52',spider:'#26323a',skeleton:'#ddd6bf',magma:'#d56d38',piglin:'#e59481',wither:'#30343b',blaze:'#f2b547',silverfish:'#a8a69a',endermite:'#75488a',enderman:'#1f1931'})[monster.type];ctx.fillStyle=c;ctx.fillRect(monster.x,monster.y,monster.w,monster.h);ctx.fillStyle='rgba(255,255,255,.7)';ctx.fillRect(monster.x+5,monster.y+7,4,4);ctx.fillRect(monster.x+monster.w-9,monster.y+7,4,4);if(monster.type==='spider'||monster.type==='silverfish'){ctx.fillStyle=c;ctx.fillRect(monster.x-5,monster.y+monster.h-6,5,3);ctx.fillRect(monster.x+monster.w,monster.y+monster.h-6,5,3)}}
    for (const boss of t.bosses) if (boss.alive) { ctx.fillStyle=boss.type==='blazeBoss'?'#f0a93b':boss.type==='shulker'?'#aa70bd':'#9b5547';ctx.fillRect(boss.x,boss.y,boss.w,boss.h);ctx.fillStyle='#fff2a1';ctx.fillRect(boss.x+7,boss.y+10,7,7);ctx.fillRect(boss.x+28,boss.y+10,7,7);ctx.fillStyle='#f4e8dc';ctx.fillText(`B${boss.hp}`,boss.x,boss.y-6); }
    if (t.dragon?.alive) { const d=t.dragon; ctx.fillStyle='#241a38';ctx.fillRect(d.x,d.y+17,95,30);ctx.fillRect(d.x+65,d.y+4,29,22);ctx.fillStyle='#5a3b78';ctx.fillRect(d.x-33,d.y+20,38,9);ctx.fillRect(d.x+20,d.y-8,45,10);ctx.fillStyle='#d864df';ctx.fillRect(d.x+76,d.y+10,5,5); }
    for (const shot of projectiles) {ctx.fillStyle=shot.enemy?'#d458d3':'#f5e4a4';ctx.fillRect(shot.x,shot.y,shot.w,shot.h)}
    if (!(player.invuln && Math.floor(player.invuln/6)%2===0)) { ctx.fillStyle='#5e432b';ctx.fillRect(player.x,player.y+10,player.w,32);ctx.fillStyle='#efb28c';ctx.fillRect(player.x+5,player.y,20,18);ctx.fillStyle='#4d7fbd';ctx.fillRect(player.x+3,player.y+25,24,17);ctx.fillStyle='#222';ctx.fillRect(player.x+(player.facing>0?19:8),player.y+7,4,4); }
    ctx.restore();
    ctx.fillStyle='rgba(5,15,8,.74)';ctx.fillRect(14,14,600,82);ctx.fillStyle='#eef7d8';ctx.font='bold 17px sans-serif';ctx.fillText(t.name,28,40);ctx.fillStyle='#b7d88b';ctx.font='13px sans-serif';ctx.fillText(`${t.gem}：${player.gems}/${t.gems.length}`,28,63);ctx.fillStyle=totalLives<=3?'#f06f61':'#f7c4bd';ctx.fillText(`剩余生命：${totalLives}/${selectedLives}`,180,63);ctx.fillStyle='#9fd6ef';ctx.fillText(`时间：${String(Math.floor(runTimeLeft()/60)).padStart(2,'0')}:${String(runTimeLeft()%60).padStart(2,'0')}`,28,84);ctx.fillStyle='#f1c451';ctx.fillText(`积分：${score}`,150,84);if(t.dragon?.alive){ctx.fillStyle='#ed85ea';ctx.fillText(`末影龙生命：${'■'.repeat(Math.ceil(t.dragon.hp/2))}${'□'.repeat(10-Math.ceil(t.dragon.hp/2))}`,290,84)}
    if(messageTimer>0){ctx.fillStyle='rgba(7,17,10,.8)';ctx.fillRect(120,475,720,40);ctx.fillStyle='#eff7dc';ctx.font='14px sans-serif';ctx.textAlign='center';ctx.fillText(message,480,501);ctx.textAlign='left'}
    if(!running && endingStart){const elapsed=performance.now()-endingStart,phase=Math.min(3,Math.floor(elapsed/2600));ctx.fillStyle='rgba(4,10,6,.82)';ctx.fillRect(0,0,W,H);const scenes=[['出生点','一棵橡树下，你迈出了第一步。'],['烈焰与深渊','矿洞、下界与要塞，都没能让你停下。'],['终末之战','末影龙陨落。新的传说从此开始。'],['远征完成','从出生点到末地，方块世界见证了你的旅程。']];ctx.fillStyle='#e8f4ce';ctx.font='bold 36px sans-serif';ctx.textAlign='center';ctx.fillText(scenes[phase][0],480,205);ctx.font='17px sans-serif';ctx.fillStyle='#c8dfb9';ctx.fillText(scenes[phase][1],480,247);if(phase===3){const shown=Math.min(finalScoreTarget,Math.floor(finalScoreTarget*Math.min(1,(elapsed-7800)/1800)));ctx.font='bold 28px "Press Start 2P",monospace';ctx.fillStyle='#f3ca57';ctx.fillText(`总得分 ${shown}`,480,295);}ctx.font='13px sans-serif';ctx.fillStyle='#a7bf9a';ctx.fillText('点击“重开本关”可重新开始远征',480,350);ctx.textAlign='left'}
  }
  function loop(now) { if (now-last > 15) { update(); draw(); last=now; } requestAnimationFrame(loop); }
  function showMenu() { if(running && level) recordRun('中途退出'); running=false; modeMenu.hidden=false; quizApp.hidden=true; gameApp.hidden=true; }
  function showQuiz() { modeMenu.hidden=true; quizApp.hidden=false; gameApp.hidden=true; }
  function showGame() { running=false; document.getElementById('difficultyModal').hidden=false; }
  function beginAdventure(lives, difficulty = 'normal') { selectedLives=lives; selectedDifficulty=difficulty; document.getElementById('difficultyModal').hidden=true; modeMenu.hidden=true; quizApp.hidden=true; gameApp.hidden=false; startLevel(0, false); running=true; if(!musicOn) toggleMusic(); }
  document.getElementById('openQuiz').addEventListener('click',showQuiz); document.getElementById('openGame').addEventListener('click',showGame); document.getElementById('backFromQuiz').addEventListener('click',showMenu); document.getElementById('backFromGame').addEventListener('click',showMenu); document.getElementById('musicToggle').addEventListener('click',toggleMusic); document.querySelectorAll('.difficulty-choices [data-lives]').forEach(button=>button.addEventListener('click',()=>beginAdventure(Number(button.dataset.lives), button.dataset.difficulty || 'normal'))); document.getElementById('gameRestart').addEventListener('click',()=>{if(!running) startLevel(0, false); else startLevel(levelIndex); running=true});
  const touchControls=document.getElementById('touchControls'), touchPointerKeys=new Map(), touchKeys=['ArrowLeft','ArrowRight','Space'];
  function refreshTouchKeys(){touchKeys.forEach(key=>{const held=[...touchPointerKeys.values()].includes(key); if(held||keyboardKeys.has(key))keys.add(key); else keys.delete(key);});document.querySelectorAll('.touch-controls button[data-key]').forEach(button=>button.classList.toggle('is-active',[...touchPointerKeys.values()].includes(button.dataset.key)));}
  function touchButtonAt(x,y,moveOnly=false){let best=null,bestDistance=Infinity;document.querySelectorAll('.touch-controls button:not([hidden])').forEach(button=>{if(moveOnly&&!['ArrowLeft','ArrowRight'].includes(button.dataset.key))return;const rect=button.getBoundingClientRect(),pad=22,left=rect.left-pad,right=rect.right+pad,top=rect.top-pad,bottom=rect.bottom+pad;if(x>=left&&x<=right&&y>=top&&y<=bottom){const cx=rect.left+rect.width/2,cy=rect.top+rect.height/2,dist=Math.hypot(x-cx,y-cy);if(dist<bestDistance){best=button;bestDistance=dist;}}});return best;}
  if(touchControls){const press=event=>{const button=touchButtonAt(event.clientX,event.clientY);if(!button)return;event.preventDefault();try{touchControls.setPointerCapture?.(event.pointerId)}catch{}if(button.id==='touchFire'){fire();return;}const key=button.dataset.key;touchPointerKeys.set(event.pointerId,key);if(key==='Space')jump();refreshTouchKeys();};const move=event=>{if(!touchPointerKeys.has(event.pointerId))return;event.preventDefault();const oldKey=touchPointerKeys.get(event.pointerId),button=touchButtonAt(event.clientX,event.clientY,oldKey==='ArrowLeft'||oldKey==='ArrowRight');if(button&&['ArrowLeft','ArrowRight'].includes(button.dataset.key)&&button.dataset.key!==oldKey){touchPointerKeys.set(event.pointerId,button.dataset.key);refreshTouchKeys();}};const release=event=>{if(!touchPointerKeys.has(event.pointerId))return;event.preventDefault();touchPointerKeys.delete(event.pointerId);refreshTouchKeys();};touchControls.addEventListener('pointerdown',press);touchControls.addEventListener('pointermove',move);touchControls.addEventListener('pointerup',release);touchControls.addEventListener('pointercancel',release);touchControls.addEventListener('lostpointercapture',release);}
  window.addEventListener('contextmenu',(event)=>{if(event.target.closest?.('.game-app,.difficulty-modal'))event.preventDefault();});
  window.addEventListener('selectstart',(event)=>{if(event.target.closest?.('.game-app,.difficulty-modal'))event.preventDefault();});
  window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','Space','KeyA','KeyD','KeyW','KeyF'].includes(e.code))e.preventDefault();keyboardKeys.add(e.code);keys.add(e.code);if(['Space','ArrowUp','KeyW'].includes(e.code)&&!e.repeat)jump();if(e.code==='KeyF'&&!e.repeat)fire()});window.addEventListener('keyup',e=>{keyboardKeys.delete(e.code);if(touchKeys.includes(e.code))refreshTouchKeys();else keys.delete(e.code);}); renderRunHistory(); requestAnimationFrame(loop);
})();
